apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rb-api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: henlo.info
    http:
      paths:
      - backend:
          service:
            name: rb-backend
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
      - hostname: localhost
